#pragma once

/* RGBLIGHT configuration */
#define WS2812_DI_PIN A9
#define RGBLIGHT_SPLIT
#define RGBLIGHT_LED_COUNT 2
//#define RGBLED_NUM 2
#define RGBLED_MAP { 1, 0 }
#define RGBLED_SPLIT { 1, 1 }
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LIMIT_VAL 65
#define RGBLIGHT_MAX_LAYERS 6
#define RRGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
//#define RGBLIGHT_EFFECT_TWINKLE
//#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_BREATHE_MAX 70
#define RGBLIGHT_EFFECT_BREATHE_CENTER 1.7
#define RGBLIGHT_DEFAULT_HUE 148
#define RGBLIGHT_DEFAULT_SAT 180
#define RGBLIGHT_DEFAULT_MODE RRGBLIGHT_EFFECT_BREATHING 1

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define FORCE_NKRO

#define SPLIT_HAND_PIN B7

#define USB_VBUS_PIN A10

#define EE_HANDS
//qmk config set hand left
//#define SPLIT_USB_DETECT
//#define SPLIT_USB_TIMEOUT 5500
//#define SPLIT_USB_DETECT_TRIES 5
//#define SPLIT_USB_DETECT_DELAY 1000
//#define MASTER_LEFT
//#define MASTER_RIGHT
//#define NO_USB_STARTUP_CHECK
